name: Build and Publish Actions
concurrency:
  group: 'build-commit'
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - '**/*.js'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: go to the changed directories and install dependencies
        run: |
          for dir in ${{ steps.changed-files.outputs.all_changed_files }}; do
            dir=$(dirname "$dir")
            if [ -d "$dir" ]; then
              echo "Installing dependencies in $dir"
              cd "$dir"
              npm install && npm run build
              cd -
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'actions-bot'
          git config --global user.email 'actions-bot@github.com'
          git diff --exit-code || (
            git add . && \
            git commit -m "Automated build and commit by GitHub Actions [skip ci]" && \
            git push origin main || echo "No changes to commit"
          )
