name: PR Title Validation

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate PR title
        uses: srajasimman/github-actions/pr-title-check@main
        with:
          allowed-types: "fix,feat,test,docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
